import { Metadata } from "next";
import Link from "next/link";
import { ChevronLeft } from "lucide-react";

export const metadata: Metadata = {
  title: "FAQ - PB Lucky Draw AI | Powerball Number Generator Questions",
  description: "Frequently asked questions about PB Lucky Draw AI's Powerball number generator. Learn about our AI strategies, hot/cold numbers, and how to use our free lottery picker.",
  keywords: [
    "powerball faq",
    "lottery number generator help",
    "how to pick powerball numbers",
    "lottery strategy questions",
    "powerball tips",
  ],
  alternates: {
    canonical: "/faq",
  },
};

const faqs = [
  {
    question: "What is PB Lucky Draw AI?",
    answer: "PB Lucky Draw AI is a free Powerball number generator that uses pattern analysis based on historical lottery data. It offers multiple strategies including hot numbers, cold numbers, balanced picks, and more to help you choose your lottery numbers for entertainment purposes."
  },
  {
    question: "Is PB Lucky Draw AI free to use?",
    answer: "Yes, PB Lucky Draw AI is completely free to use. There are no hidden fees, subscriptions, or premium features. Generate as many number combinations as you like at no cost."
  },
  {
    question: "What are hot and cold numbers?",
    answer: "Hot numbers are Powerball numbers that have appeared more frequently in recent drawings. Cold numbers are those that haven't been drawn as often. Our Super Hot strategy focuses on frequently drawn numbers, while the Contrarian strategy uses cold numbers that are statistically 'due' to appear."
  },
  {
    question: "What strategies does PB Lucky Draw AI offer?",
    answer: "We offer six unique strategies: Ultimate AI (our best balanced algorithm), Super Hot (frequently drawn numbers), Contrarian (cold numbers), Balanced (optimal mix of hot/cold), Frequency-Weighted (probability-based), and Pure Random (true randomization)."
  },
  {
    question: "Can PB Lucky Draw AI guarantee winning numbers?",
    answer: "No. The lottery is fundamentally random, and no system can predict or guarantee winning numbers. PB Lucky Draw AI is designed for entertainment purposes only. Past patterns do not predict future results. Always play responsibly and within your means."
  },
  {
    question: "How does the Ultimate AI strategy work?",
    answer: "The Ultimate AI strategy combines multiple factors including historical frequency analysis, recent trend data, number distribution patterns, and mathematical balancing to generate numbers. It aims to create well-rounded combinations that follow observed patterns in lottery data."
  },
  {
    question: "Are my generated numbers saved?",
    answer: "Yes, your generated numbers and saved sets are stored locally in your browser. They will persist even after you close the page or refresh. You can save multiple sets and clear them anytime you want."
  },
  {
    question: "What is the generation counter?",
    answer: "The generation counter shows how many total number combinations have been generated by all users of PB Lucky Draw AI worldwide. It's a fun way to see the community's activity."
  },
  {
    question: "How often is the pattern data updated?",
    answer: "Our pattern analysis is based on comprehensive historical Powerball data. The hot/cold number classifications and frequency data reflect patterns from thousands of past drawings."
  },
  {
    question: "Can I use these numbers for actual lottery tickets?",
    answer: "You can use any numbers you like for your lottery tickets. However, remember that PB Lucky Draw AI is for entertainment only. The lottery is random, and we make no claims about improving your odds of winning. Play responsibly."
  }
];

const faqJsonLd = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  "mainEntity": faqs.map(faq => ({
    "@type": "Question",
    "name": faq.question,
    "acceptedAnswer": {
      "@type": "Answer",
      "text": faq.answer
    }
  }))
};

export default function FAQPage() {
  return (
    <main className="min-h-screen bg-background">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }}
      />
      
      <div className="container mx-auto px-4 py-8 md:py-12 max-w-3xl">
        <Link 
          href="/" 
          className="inline-flex items-center text-sm text-muted-foreground hover:text-foreground mb-6 transition-colors"
        >
          <ChevronLeft className="w-4 h-4 mr-1" />
          Back to Generator
        </Link>
        
        <h1 className="text-3xl md:text-4xl font-bold mb-2 text-foreground">
          Frequently Asked Questions
        </h1>
        <p className="text-muted-foreground mb-8">
          Everything you need to know about PB Lucky Draw AI
        </p>

        <div className="space-y-6">
          {faqs.map((faq, index) => (
            <div 
              key={index} 
              className="border border-border rounded-lg p-5 bg-card/50"
            >
              <h2 className="text-lg font-semibold mb-2 text-foreground">
                {faq.question}
              </h2>
              <p className="text-muted-foreground leading-relaxed">
                {faq.answer}
              </p>
            </div>
          ))}
        </div>

        <div className="mt-12 text-center">
          <p className="text-muted-foreground mb-4">Ready to try your luck?</p>
          <Link 
            href="/"
            className="inline-flex items-center justify-center px-6 py-3 bg-primary text-primary-foreground font-medium rounded-full hover:opacity-90 transition-opacity"
          >
            Generate Numbers Now
          </Link>
        </div>
      </div>
    </main>
  );
}
